# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'Batch' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Batch
    pod 'SVProgressHUD'
    pod 'IQKeyboardManagerSwift'
    pod "SGCodeTextField"
    pod 'FSCalendar'
    pod 'SwiftyStarRatingView'
    pod 'HCVimeoVideoExtractor'
    pod 'SDWebImage'
    pod 'GoogleSignIn'
    pod 'DropDown'
    pod 'MyFatoorah'
    pod 'DGCharts'
    pod "ImageSlideshow/SDWebImage"

    #Pods for Firebase
    pod 'Firebase/Core'
    pod 'Firebase/Messaging'
    pod 'Firebase/Crashlytics'

    target 'BatchTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BatchUITests' do
    # Pods for testing
  end
  
  post_install do |installer|
       installer.generated_projects.each do |project|
             project.targets.each do |target|
                 target.build_configurations.each do |config|
                     config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
                  end
             end
      end
   end
end
